[ci]: functional test with O0 or O2

diff --git a/.github/workflows/auto-test.yml b/.github/workflows/auto-test.yml
--- a/.github/workflows/auto-test.yml
+++ b/.github/workflows/auto-test.yml
@@ -44,6 +44,9 @@ jobs:
 
   functional-test:
     needs: compile
+    strategy:
+      matrix:
+        opt: [0, 2]
     runs-on: ubuntu-latest
 
     steps:
@@ -89,17 +92,15 @@ jobs:
         run: |
           chmod +x ${{github.workspace}}/tests/*.sh
           chmod +x ${{github.workspace}}/tests/*.py
-          ctest -C ${{env.BUILD_TYPE}} -R Functional-*
+          ctest -C ${{env.BUILD_TYPE}} -R Functional-LLVM-O${{matrix.opt}}*
 
       - name: Summary
         if: always()
         run: |
-          echo "## Functional Test Summary:" >> $GITHUB_STEP_SUMMARY
-          echo "| Test Name | Passed | Failed |" >> $GITHUB_STEP_SUMMARY
-          echo "|-----------|--------|--------|" >> $GITHUB_STEP_SUMMARY
-          sed -n 1p ${{github.workspace}}/tests/functional.log >> $GITHUB_STEP_SUMMARY || true
-          sed -n 1p ${{github.workspace}}/tests/hidden_functional.log >> $GITHUB_STEP_SUMMARY || true
+          echo "## Functional Test Summary (-O${{matrix.opt}}):" >> $GITHUB_STEP_SUMMARY
+          echo "| Test Name | Passed | Failed | Failures |" >> $GITHUB_STEP_SUMMARY
+          echo "|-----------|--------|--------| -------- |" >> $GITHUB_STEP_SUMMARY
+          cat ${{github.workspace}}/tests/functional.log >> $GITHUB_STEP_SUMMARY || true
+          cat ${{github.workspace}}/tests/hidden_functional.log >> $GITHUB_STEP_SUMMARY || true
           echo '' >> $GITHUB_STEP_SUMMARY
-          sed -n 2p ${{github.workspace}}/tests/functional.log >> $GITHUB_STEP_SUMMARY || true
-          sed -n 2p ${{github.workspace}}/tests/hidden_functional.log >> $GITHUB_STEP_SUMMARY || true
           echo '' >> $GITHUB_STEP_SUMMARY
